apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: suxess-it-dev-poi-map-app-dev
  annotations:
    argocd/app-name: suxess-it-dev-poi-map-app-dev
    backstage.io/kubernetes-id: suxess-it-dev-poi-map-app-dev
    backstage.io/kubernetes-namespace: suxess-it-dev
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=suxess-it-dev-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: phac008/suxess-it-dev-frontend
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.cluster1.mcp.pitagora.at/dev-pipelines/ns/suxess-it-dev/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.cluster1.mcp.pitagora.at/k8s/ns/suxess-it-dev/deployments/poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.cluster1.mcp.pitagora.at/#https://github.com/phac008/suxess-it-dev-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "guests"
  system: workshop-system-suxess-it-dev
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-suxess-it-dev
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "guests"
